# La imagen base es node en la versión indicada en el tag
FROM node:20.11.1-alpine3.19
RUN mkdir -p /opt/app
WORKDIR /opt/app
COPY package.json .
RUN npm install
COPY src/ .
EXPOSE 3000
CMD [ "node", "app.js" ]
